name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: corepack enable

      - run: pnpm install --no-frozen-lockfile --ignore-scripts
      - run: pnpm run sync
      - run: pnpm run check || true

  publish:
    needs: check
    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org

      - run: corepack enable

      - run: pnpm install --no-frozen-lockfile --ignore-scripts
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
